# Generated by Django 5.0.1 on 2024-01-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('account_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Issue'), ('RECEIVE', 'Receive')], max_length=10)),
                ('remarks', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wastage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ACCOUNT_NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher'),
        ),
    ]
